<style>
    .module-container {
        width: 80%;
        margin-left: auto;
        margin-right: auto;
    }
</style>
<div class="module-container" >
    <h2><strong>Dự báo thời tiết</strong></h2>
<div id="openweathermap-widget-11"></div>
<script src='//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/d3.min.js'></script>
<script>window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];
    window.myWidgetParam.push({
        id: 11,
        cityid: '1581129',
        appid: '93023d1e4a5870d00c2abde87b1a93ee',
        units: 'metric',
        containerid: 'openweathermap-widget-11',
    });
    (function () {
        var script = document.createElement('script');
        script.async = true;
        script.charset = "utf-8";
        script.src = "//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js";
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(script, s);
    })();</script>
</div>